# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XK7wIpvqFw5bCC-f2i4EaB2aEJ8ehw7G
"""

Вод как создавались чанки
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Загрузите все PDF файлы
uploaded = files.upload()

# Список для всех документов
all_docs = []

# Загрузите каждый PDF
for filename in uploaded.keys():
    loader = PyPDFLoader(filename)
    docs = loader.load()
    all_docs.extend(docs)

print(f"Загружено {len(all_docs)} страниц из {len(uploaded)} книг")

from langchain_text_splitters import RecursiveCharacterTextSplitter

# Разделите все документы на чанки
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)

chunks = text_splitter.split_documents(all_docs)
print(f"Создано {len(chunks)} чанков")

# ============ ИСПОЛЬЗОВАНИЕ ============
if name == "main":
    print("🚀 КЛАССИФИКАЦИЯ ЧАНКОВ\n")

    # Убедись, что chunks уже загружены (твой исходный код)
    # chunks должна быть готовой переменной перед этим

    if 'chunks' not in locals():
        print("❌ Ошибка: переменная 'chunks' не найдена!")
        print("Убедись, что ты загрузил и разбил документы ДО этого кода")
        exit(1)

    # Выбор режима
    print("Выбери режим:")
    print("1 - с двойной валидацией (медленно, но точнее)")
    print("2 - только Pass1 (быстро, но менее точно)")
    mode = input("\nТвой выбор (1 или 2): ").strip()
    validate_mode = mode != "2"

    # Классифицируй чанки
    classifier = ChunkClassifier(model=classifier_model, validate=validate_mode)
    classified_chunks = classifier.classify_chunks(chunks, verbose=True)

    # Статистика
    stats = classifier.get_statistics()
    print("\n" + "=" * 60)
    print("📊 СТАТИСТИКА КЛАССИФИКАЦИИ:")
    print("=" * 60)
    print(f"Всего чанков: {stats['total_chunks']}")
    print(f"Pass1 точность: {stats['pass1_accuracy']}")
    print(f"Разногласий: {stats['disagreements']} ({stats['disagreement_rate']})")
    print("\nРаспределение по темам:")
    for topic, count in stats['by_topic'].items():
        print(f"  {topic}: {count}")