# -*- coding: utf-8 -*-
"""Метрики.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XK7wIpvqFw5bCC-f2i4EaB2aEJ8ehw7G
"""

test_cases_1 = []
for i, question in enumerate(simple_c_questions_20, 1):
    config = {"configurable": {"thread_id": f"simple-{i}"}}
    result = agent.invoke({"messages": [HumanMessage(content=question)]}, config)

    rag_results = {}
    for msg in result["messages"]:
        if hasattr(msg, 'name') and msg.name and hasattr(msg, 'content') and msg.content.strip():
            rag_results[msg.name] = msg.content.strip()

    rag_context = list(rag_results.values())
    tools_used = list(rag_results.keys())
    agent_output = result["messages"][-1].content

    test_case = LLMTestCase(
        input=question,
        retrieval_context=rag_context,
        actual_output=f"Tools: {tools_used}\n\nОтвет: {agent_output}"
    )
    test_cases_simple_20.append(test_case)

print(f"\n✅ 20 ПРОСТЫХ test cases готовы!")


test_cases_2 = []
c_2questions_20 = [
    "Как написать if условие?",
    "Что такое typedef в C?",
    "Как работает continue?",
    "Что возвращает функция void?",
    "Как объявить двумерный массив?",
    "Разница malloc и calloc?",
    "Как передать массив в функцию?",
    "Что такое рекурсия?",
    "Как использовать #include?",
    "Что такое локальные переменные?",
    "Как получить размер массива?",
    "Что означает const?",
    "Что такое static переменные?",
    "Как использовать enum?",
    "Что такое union?",
    "Как проверить указатель на NULL?",
    "sizeof для структур?",
    "Как копировать строку в C?",
    "fopen для чтения файла?",
    "Как работает fprintf()?"
]

for i, question in enumerate(new_questions_20, 1):
    print(f"🧪 New Test {i}: {question}")

    config = {"configurable": {"thread_id": f"new-{i}"}}
    result = agent.invoke({"messages": [HumanMessage(content=question)]}, config)

    rag_results = {}
    for msg in result["messages"]:
        if hasattr(msg, 'name') and msg.name and hasattr(msg, 'content') and msg.content.strip():
            rag_results[msg.name] = msg.content.strip()

    rag_context = list(rag_results.values())
    tools_used = list(rag_results.keys())
    agent_output = result["messages"][-1].content

    test_case = LLMTestCase(
        input=question,
        retrieval_context=rag_context,
        actual_output=f"Tools: {tools_used}\n\nОтвет: {agent_output}"
    )
    test_cases.append(test_case)
    print(f"  📦 Tools: {tools_used}")

print(f"\n✅ Новые 20 test cases готовы!")

Александр Волков, [16.12.2025 19:41]
# Contextual Precision GEval
contextual_precision_geval = GEval(
    name="Contextual Precision",
    criteria="Оцените релевантность контекста вопросу.",
    model=eval_model,
    evaluation_steps=[
         "Проверьте тематическое соответствие retrieval_context вопросу input",
        "Требуется хорошее совпадение ключевых понятий C-программирования",
        "Контекст должен содержать релевантную техническую информацию",
        "Высокий балл при точном соответствии тематики вопроса и контекста"
    ],
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.RETRIEVAL_CONTEXT],
)


answer_relevancy_geval = GEval(
    name="Answer Relevancy",
    criteria="Оцените релевантность ответа агента вопросу.",
    model=eval_model,
    evaluation_steps=[
        "Сравните actual_output (ответ агента) с input (вопросом)",
        "Ответ должен прямо отвечать на поставленный вопрос",
        "Оцените полноту и точность покрытия запрошенной информации",
        "Высокий балл при прямом соответствии ответа содержанию вопроса"
    ],
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.ACTUAL_OUTPUT],
)


faithfulness_geval = GEval(
    name="Faithfulness",
    criteria="Оцените достоверность ответа относительно предоставленного контекста.",
    model=eval_model,
    evaluation_steps=[
        "Проверьте, основан ли actual_output на фактах из retrieval_context",
        "Ответ не должен содержать информации, отсутствующей в контексте",
        "Штрафуйте за галлюцинации и выдуманные факты",
        "Высокий балл если ответ строго следует предоставленной информации"
    ],
    evaluation_params=[LLMTestCaseParams.RETRIEVAL_CONTEXT, LLMTestCaseParams.ACTUAL_OUTPUT],
)


# GEval Tool Correctness
tool_correctness = GEval(
    name="Tool Correctness",
    criteria="Оцени правильность выбора RAG tools для вопроса по C программированию.",
    model=eval_model,
    evaluation_steps=[
        "В 'input' - вопрос пользователя",
        "В 'retrieval_context' - результаты вызванных tools",
        "В 'actual_output' - список использованных tools + ответ агента",
        "syntax_search = переменные/типы/printf",
        "control_flow_search = циклы/if/switch",
        "data_structures_search = указатели/массивы/struct",
        "functions_search = функции/прототипы",
        "memory_files_search = malloc/файлы",
        "1 tool = простой вопрос, 2-3 tools = сложный",
        "Высокий score если tools релевантны вопросу"
    ],
    evaluation_params=[LLMTestCaseParams.INPUT, LLMTestCaseParams.RETRIEVAL_CONTEXT, LLMTestCaseParams.ACTUAL_OUTPUT],
)